name: Build, Push & Promote to JFrog

on:
  push:
    branches:
      - main

jobs:
  build-and-promote:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to JFrog
        uses: docker/login-action@v3
        with:
          registry: trial08wn7n.jfrog.io
          username: ${{ secrets.JFROG_USERNAME }}
          password: ${{ secrets.JFROG_TOKEN }}

      - name: Build Docker image
        run: |
          docker build \
            -t trial08wn7n.jfrog.io/docker-trial/jfrog-demo:${{ github.sha }} .

      - name: Push Docker image
        run: |
          docker push \
            trial08wn7n.jfrog.io/docker-trial/jfrog-demo:${{ github.sha }}

- name: Setup JFrog CLI
  uses: jfrog/setup-jfrog-cli@v4

- name: Configure JFrog authentication
  run: |
    printf '%s' "${{ secrets.JFROG_TOKEN }}" | jf config add jfrog \
      --url=https://trial08wn7n.jfrog.io \
      --access-token-stdin \
      --interactive=false \
      --overwrite

- name: Test JFrog connection
  run: |
    jf rt ping --server-id=jfrog