name: Build, Push & Promote to JFrog

on:
  push:
    branches:
      - main

jobs:
  build-and-promote:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to JFrog
        uses: docker/login-action@v3
        with:
          registry: trial08wn7n.jfrog.io
          username: ${{ secrets.JFROG_USERNAME }}
          password: ${{ secrets.JFROG_TOKEN }}

      - name: Build Docker image
        run: |
          docker build \
            -t trial08wn7n.jfrog.io/docker-trial/jfrog-demo:${{ github.sha }} .

      - name: Push Docker image
        run: |
          docker push \
            trial08wn7n.jfrog.io/docker-trial/jfrog-demo:${{ github.sha }}

      - name: Configure JFrog CLI
        uses: jfrog/setup-jfrog-cli@v4
        env:
          JF_URL: https://trial08wn7n.jfrog.io
          JF_ACCESS_TOKEN: ${{ secrets.JFROG_TOKEN }}

      - name: Promote Build
        run: |
          jf rt bpr jfrog-demo ${{ github.run_number }} docker-prod \
            --source-repo=docker-trial \
            --copy \
            --status=Released \
            --comment="Automatically promoted by GitHub Actions"